{% set name = "drm4g" %}
{% set version = "3.0.13" %}
{% set sha256 = "5efa8f8301d04f9eca388d6a1de8ffb507128a5a410d708ff41f54e6a886f6b6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/drm4g-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [not linux]
  entry_points:
    - drm4g=drm4g.commands.main:main
    - gw_im_mad_drm4g.py=drm4g.core.im_mad:main
    - gw_em_mad_drm4g.py=drm4g.core.em_mad:main
    - gw_tm_mad_drm4g.py=drm4g.core.tm_mad:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
  host:
    - pip
    - python
  run:
    - fabric
    - paramiko >=2.4
    - python
    - scp

test:
  imports:
    - drm4g
  commands:
    - pip check
    - drm4g --help
    - gw_im_mad_drm4g.py --help
    - gw_em_mad_drm4g.py --help
    - gw_tm_mad_drm4g.py --help
  requires:
    - pip

about:
  home: https://github.com/SantanderMetGroup/DRM4G
  summary: Meta-scheduling framework for distributed computing infrastructures
  dev_url: https://github.com/SantanderMetGroup/DRM4G
  license: EUPL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cofinoa
